# This should always correspond to the earliest non-EOL Ruby version.
AllCops:
  TargetRubyVersion: 2.4

# TODO: Re-enable this cop after TomDoc code deocumentation is added.
Style/Documentation:
  Enabled: false

# Allow some style changes in the specs.
Metrics/BlockLength:
  Exclude:
    - figaro.gemspec
    - spec/**/*
Metrics/ModuleLength:
  Exclude:
    - spec/**/*
Layout/LineLength:
  Exclude:
    - figaro.gemspec
    - spec/**/*

# These style conventions are personal preference.
Layout/ArgumentAlignment:
  EnforcedStyle: with_fixed_indentation
Layout/ClosingHeredocIndentation:
  Enabled: false
Layout/FirstHashElementIndentation:
  EnforcedStyle: consistent
Layout/HashAlignment:
  EnforcedLastArgumentHashStyle: ignore_implicit
Layout/MultilineMethodCallIndentation:
  EnforcedStyle: indented
Layout/MultilineOperationIndentation:
  EnforcedStyle: indented
Layout/ParameterAlignment:
  EnforcedStyle: with_fixed_indentation
Naming/HeredocDelimiterNaming:
  Enabled: false
Naming/RescuedExceptionsVariableName:
  PreferredName: error
Style/DoubleNegation:
  Enabled: false
Style/StringLiterals:
  EnforcedStyle: double_quotes
Style/SymbolArray:
  EnforcedStyle: brackets
Style/WordArray:
  EnforcedStyle: brackets
